// SPDX-FileCopyrightText: Copyright 2025 RdenBlaauwen; Jorge Jimenez et al.; NVIDIA Corporation; Derek Brush
// SPDX-License-Identifier: LicenseRef-PSMAA-ThirdParty

#version 450
#extension GL_EXT_spirv_intrinsics : require
#if defined(GL_EXT_control_flow_attributes)
#extension GL_EXT_control_flow_attributes : require
#define SPIRV_CROSS_FLATTEN [[flatten]]
#define SPIRV_CROSS_BRANCH [[dont_flatten]]
#define SPIRV_CROSS_UNROLL [[unroll]]
#define SPIRV_CROSS_LOOP [[dont_unroll]]
#else
#define SPIRV_CROSS_FLATTEN
#define SPIRV_CROSS_BRANCH
#define SPIRV_CROSS_UNROLL
#define SPIRV_CROSS_LOOP
#endif
#ifndef PSMAA_LUMA_FORMAT
#define PSMAA_LUMA_FORMAT r16f
#endif
#ifndef PSMAA_VECTOR_FORMAT
#define PSMAA_VECTOR_FORMAT rg16f
#endif
#ifndef CMAA_EDGE_FORMAT
#define CMAA_EDGE_FORMAT r8ui
#endif

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

float _94;

layout(push_constant, std430) uniform type_PushConstant_Constants
{
    vec4 metrics;
    vec4 target;
    uint conversion;
} params;

layout(set = 0, binding = 0) uniform texture2D tex0;
layout(set = 0, binding = 1) uniform texture2D tex1;
layout(set = 0, binding = 2) uniform texture2D tex2;
layout(set = 0, binding = 3) uniform texture2D tex3;
layout(set = 0, binding = 8) uniform sampler point_sampler;
layout(set = 0, binding = 9) uniform sampler linear_sampler;
layout(set = 0, binding = 10, rgba16f) uniform writeonly image2D output0;

spirv_instruction(set = "GLSL.std.450", id = 79) float spvNMin(float, float);
spirv_instruction(set = "GLSL.std.450", id = 79) vec2 spvNMin(vec2, vec2);
spirv_instruction(set = "GLSL.std.450", id = 79) vec3 spvNMin(vec3, vec3);
spirv_instruction(set = "GLSL.std.450", id = 79) vec4 spvNMin(vec4, vec4);
spirv_instruction(set = "GLSL.std.450", id = 80) float spvNMax(float, float);
spirv_instruction(set = "GLSL.std.450", id = 80) vec2 spvNMax(vec2, vec2);
spirv_instruction(set = "GLSL.std.450", id = 80) vec3 spvNMax(vec3, vec3);
spirv_instruction(set = "GLSL.std.450", id = 80) vec4 spvNMax(vec4, vec4);

void main()
{
    do
    {
        if (any(greaterThanEqual(gl_GlobalInvocationID.xy, uvec2(params.target.zw))))
        {
            break;
        }
        vec2 _113 = (vec2(gl_GlobalInvocationID.xy) + vec2(0.5)) * params.metrics.xy;
        vec4 _117 = textureLod(sampler2D(tex0, linear_sampler), _113, 0.0);
        precise vec4 _17 = fma(vec4(params.metrics.x, params.metrics.y, _94, _94).xyxy, vec4(1.0, 0.0, 0.0, 1.0), _113.xyxy);
        vec3 _646;
        bool _647;
        do
        {
            vec4 _134 = textureGather(sampler2D(tex1, point_sampler), _113);
            vec4 _137 = textureGather(sampler2D(tex1, point_sampler), _113, 1);
            vec4 _142 = vec4(_134.w, _137.w, _134.z, _137.x);
            vec4 _145 = textureLod(sampler2D(tex3, linear_sampler), _113, 0.0);
            float _146 = _145.x;
            vec2 _149 = spvNMax(_142.xz, _142.yw);
            vec2 _155 = spvNMax(vec2(0.100000001490116119384765625, 0.5) * fma(1.0 - _146, -0.64999997615814208984375, 1.0), vec2(0.0599999986588954925537109375));
            float _158 = smoothstep(_155.x, _155.y, sqrt(dot(_149 * _149, vec2(1.0))));
            if (_158 < 9.9999997473787516355514526367188e-06)
            {
                _646 = _117.xyz;
                _647 = true;
                break;
            }
            uint _165 = uint(mix(5.0, 20.0, _158) + 0.5);
            vec3 _645;
            do
            {
                float _168 = _113.x;
                float _169 = _113.y;
                vec2 _171 = vec4(_168, _169, 0.0, 0.0).xy;
                vec4 _174 = textureLod(sampler2D(tex0, linear_sampler), _171, 0.0);
                vec3 _175 = _174.xyz;
                float _176 = dot(_175, vec3(0.2989999949932098388671875, 0.58700001239776611328125, 0.114000000059604644775390625));
                float _177 = _174.x;
                float _178 = _174.y;
                float _180 = _174.z;
                bool _190 = _176 > ((spvNMax(spvNMax(_177, _178), _180) - spvNMin(spvNMin(_177, _178), _180)) / ((2.0 - (2.0 * _176)) + trunc(_176)));
                float _192 = (!_190) ? 0.0 : _176;
                vec2 _194 = vec4(_168, _169, _94, _94).xy;
                vec3 _200 = textureLod(sampler2D(tex0, linear_sampler), _194 + (vec2(0.0, 1.0) * params.metrics.xy), 0.0).xyz;
                float _210;
                do
                {
                    if (_190)
                    {
                        _210 = dot(_200, vec3(0.2989999949932098388671875, 0.58700001239776611328125, 0.114000000059604644775390625));
                        break;
                    }
                    else
                    {
                        _210 = dot(abs(_175 - _200), vec3(0.2989999949932098388671875, 0.58700001239776611328125, 0.114000000059604644775390625));
                        break;
                    }
                    break; // unreachable workaround
                } while(false);
                vec3 _216 = textureLod(sampler2D(tex0, linear_sampler), _194 + (vec2(1.0, 0.0) * params.metrics.xy), 0.0).xyz;
                float _226;
                do
                {
                    if (_190)
                    {
                        _226 = dot(_216, vec3(0.2989999949932098388671875, 0.58700001239776611328125, 0.114000000059604644775390625));
                        break;
                    }
                    else
                    {
                        _226 = dot(abs(_175 - _216), vec3(0.2989999949932098388671875, 0.58700001239776611328125, 0.114000000059604644775390625));
                        break;
                    }
                    break; // unreachable workaround
                } while(false);
                vec3 _232 = textureLod(sampler2D(tex0, linear_sampler), _194 + (vec2(0.0, -1.0) * params.metrics.xy), 0.0).xyz;
                float _242;
                do
                {
                    if (_190)
                    {
                        _242 = dot(_232, vec3(0.2989999949932098388671875, 0.58700001239776611328125, 0.114000000059604644775390625));
                        break;
                    }
                    else
                    {
                        _242 = dot(abs(_175 - _232), vec3(0.2989999949932098388671875, 0.58700001239776611328125, 0.114000000059604644775390625));
                        break;
                    }
                    break; // unreachable workaround
                } while(false);
                vec3 _248 = textureLod(sampler2D(tex0, linear_sampler), _194 + (vec2(-1.0, 0.0) * params.metrics.xy), 0.0).xyz;
                float _258;
                do
                {
                    if (_190)
                    {
                        _258 = dot(_248, vec3(0.2989999949932098388671875, 0.58700001239776611328125, 0.114000000059604644775390625));
                        break;
                    }
                    else
                    {
                        _258 = dot(abs(_175 - _248), vec3(0.2989999949932098388671875, 0.58700001239776611328125, 0.114000000059604644775390625));
                        break;
                    }
                    break; // unreachable workaround
                } while(false);
                float _267 = spvNMax(spvNMax(_210, _226), spvNMax(spvNMax(_242, _258), _192)) - spvNMin(spvNMin(_210, _226), spvNMin(spvNMin(_242, _258), _192));
                if (_267 < mix(0.014999999664723873138427734375, 0.0900000035762786865234375, _146))
                {
                    _645 = _175;
                    break;
                }
                vec3 _276 = textureLod(sampler2D(tex0, linear_sampler), _194 + (vec2(-1.0) * params.metrics.xy), 0.0).xyz;
                float _286;
                do
                {
                    if (_190)
                    {
                        _286 = dot(_276, vec3(0.2989999949932098388671875, 0.58700001239776611328125, 0.114000000059604644775390625));
                        break;
                    }
                    else
                    {
                        _286 = dot(abs(_175 - _276), vec3(0.2989999949932098388671875, 0.58700001239776611328125, 0.114000000059604644775390625));
                        break;
                    }
                    break; // unreachable workaround
                } while(false);
                vec3 _291 = textureLod(sampler2D(tex0, linear_sampler), _194 + params.metrics.xy, 0.0).xyz;
                float _301;
                do
                {
                    if (_190)
                    {
                        _301 = dot(_291, vec3(0.2989999949932098388671875, 0.58700001239776611328125, 0.114000000059604644775390625));
                        break;
                    }
                    else
                    {
                        _301 = dot(abs(_175 - _291), vec3(0.2989999949932098388671875, 0.58700001239776611328125, 0.114000000059604644775390625));
                        break;
                    }
                    break; // unreachable workaround
                } while(false);
                vec3 _307 = textureLod(sampler2D(tex0, linear_sampler), _194 + (vec2(1.0, -1.0) * params.metrics.xy), 0.0).xyz;
                float _317;
                do
                {
                    if (_190)
                    {
                        _317 = dot(_307, vec3(0.2989999949932098388671875, 0.58700001239776611328125, 0.114000000059604644775390625));
                        break;
                    }
                    else
                    {
                        _317 = dot(abs(_175 - _307), vec3(0.2989999949932098388671875, 0.58700001239776611328125, 0.114000000059604644775390625));
                        break;
                    }
                    break; // unreachable workaround
                } while(false);
                vec3 _323 = textureLod(sampler2D(tex0, linear_sampler), _194 + (vec2(-1.0, 1.0) * params.metrics.xy), 0.0).xyz;
                float _333;
                do
                {
                    if (_190)
                    {
                        _333 = dot(_323, vec3(0.2989999949932098388671875, 0.58700001239776611328125, 0.114000000059604644775390625));
                        break;
                    }
                    else
                    {
                        _333 = dot(abs(_175 - _323), vec3(0.2989999949932098388671875, 0.58700001239776611328125, 0.114000000059604644775390625));
                        break;
                    }
                    break; // unreachable workaround
                } while(false);
                float _334 = _286 + _333;
                float _335 = _242 + _210;
                float _336 = _317 + _301;
                float _338 = _258 + _226;
                bool _348 = (abs(fma(-2.0, _258, _334)) + fma(2.0, abs(fma(-2.0, _192, _335)), abs(fma(-2.0, _226, _336)))) >= (abs(fma(-2.0, _210, _333 + _301)) + fma(2.0, abs(fma(-2.0, _192, _338)), abs(fma(-2.0, _242, _286 + _317))));
                float _349 = _348 ? params.metrics.y : params.metrics.x;
                vec4 _356 = textureLod(sampler2D(tex2, linear_sampler), vec4(_17.xy, 0.0, 0.0).xy, 0.0);
                float _357 = _356.w;
                vec4 _364 = textureLod(sampler2D(tex2, linear_sampler), vec4(_17.zw, 0.0, 0.0).xy, 0.0);
                float _365 = _364.y;
                vec4 _368 = textureLod(sampler2D(tex2, linear_sampler), _171, 0.0);
                float _369 = _368.z;
                float _370 = _368.x;
                bool _374 = spvNMax(_357, _369) > spvNMax(_365, _370);
                bool _376 = any(notEqual(vec4(_357, _365, _369, _370), vec4(0.0)));
                float _380 = 0.5 * spvNMax(spvNMax(_357, _365), spvNMax(_369, _370));
                float _381 = 0.5 + _380;
                bool _393;
                if (!((_348 ? _374 : false) ? _376 : false))
                {
                    bool _391;
                    if (!_348)
                    {
                        _391 = !_374;
                    }
                    else
                    {
                        _391 = false;
                    }
                    _393 = _391 ? _376 : false;
                }
                else
                {
                    _393 = true;
                }
                float _401;
                if (_393)
                {
                    _401 = _381 * (1.0 - _380);
                }
                else
                {
                    _401 = spvNMin(_381 * 1.5, 1.0);
                }
                vec2 _402 = vec2(_242, _210);
                bool _403 = !_348;
                vec2 _407;
                SPIRV_CROSS_FLATTEN
                if (_403)
                {
                    vec2 _406 = _402;
                    _406.x = _258;
                    _407 = _406;
                }
                else
                {
                    _407 = _402;
                }
                vec2 _411;
                SPIRV_CROSS_FLATTEN
                if (_403)
                {
                    vec2 _410 = _407;
                    _410.y = _226;
                    _411 = _410;
                }
                else
                {
                    _411 = _407;
                }
                float _417 = abs(_411.x - _192);
                float _418 = abs(_411.y - _192);
                float _425;
                float _426;
                if (_417 >= _418)
                {
                    _425 = _411.x + _192;
                    _426 = -_349;
                }
                else
                {
                    _425 = _411.y + _192;
                    _426 = _349;
                }
                float _427 = _426 * 0.5;
                vec2 _429 = vec2(0.0, params.metrics.y * 0.5);
                vec2 _434;
                SPIRV_CROSS_FLATTEN
                if (_348)
                {
                    vec2 _433 = _429;
                    _433.x = params.metrics.x * 0.5;
                    _434 = _433;
                }
                else
                {
                    _434 = _429;
                }
                vec2 _438;
                SPIRV_CROSS_FLATTEN
                if (_348)
                {
                    vec2 _437 = _434;
                    _437.y = 0.0;
                    _438 = _437;
                }
                else
                {
                    _438 = _434;
                }
                vec2 _444;
                SPIRV_CROSS_FLATTEN
                if (_403)
                {
                    vec2 _443 = _113;
                    _443.x = _168 + _427;
                    _444 = _443;
                }
                else
                {
                    _444 = _113;
                }
                vec2 _448;
                SPIRV_CROSS_FLATTEN
                if (_348)
                {
                    vec2 _447 = _444;
                    _447.y = _169 + _427;
                    _448 = _447;
                }
                else
                {
                    _448 = _444;
                }
                vec2 _449 = _448 - _438;
                vec2 _450 = _448 + _438;
                vec3 _458 = textureLod(sampler2D(tex0, linear_sampler), vec4(_449, 0.0, 0.0).xy, 0.0).xyz;
                float _468;
                do
                {
                    if (_190)
                    {
                        _468 = dot(_458, vec3(0.2989999949932098388671875, 0.58700001239776611328125, 0.114000000059604644775390625));
                        break;
                    }
                    else
                    {
                        _468 = dot(abs(_175 - _458), vec3(0.2989999949932098388671875, 0.58700001239776611328125, 0.114000000059604644775390625));
                        break;
                    }
                    break; // unreachable workaround
                } while(false);
                vec3 _476 = textureLod(sampler2D(tex0, linear_sampler), vec4(_450, 0.0, 0.0).xy, 0.0).xyz;
                float _486;
                do
                {
                    if (_190)
                    {
                        _486 = dot(_476, vec3(0.2989999949932098388671875, 0.58700001239776611328125, 0.114000000059604644775390625));
                        break;
                    }
                    else
                    {
                        _486 = dot(abs(_175 - _476), vec3(0.2989999949932098388671875, 0.58700001239776611328125, 0.114000000059604644775390625));
                        break;
                    }
                    break; // unreachable workaround
                } while(false);
                float _488 = spvNMax(_417, _418) * 0.25;
                bool _490 = fma(0.5, -_425, _192) < 0.0;
                float _491 = _425 * 0.5;
                float _492 = _468 - _491;
                float _493 = _486 - _491;
                bool _495 = abs(_492) >= _488;
                bool _497 = abs(_493) >= _488;
                vec2 _574;
                vec2 _575;
                float _576;
                float _577;
                if (!(_495 ? _497 : false))
                {
                    vec2 _503;
                    vec2 _506;
                    float _514;
                    float _516;
                    _503 = _450;
                    _506 = _449;
                    _514 = _492;
                    _516 = _493;
                    uint _513;
                    vec2 _504;
                    vec2 _507;
                    bool _509;
                    bool _511;
                    float _515;
                    float _517;
                    bool _508 = _497;
                    bool _510 = _495;
                    uint _512 = 0u;
                    SPIRV_CROSS_LOOP
                    for (; _512 < _165; _503 = _504, _506 = _507, _508 = _509, _510 = _511, _512 = _513, _514 = _515, _516 = _517)
                    {
                        if (_510 ? _508 : false)
                        {
                            break;
                        }
                        if (!_510)
                        {
                            vec2 _527 = _506 - _438;
                            vec3 _535 = textureLod(sampler2D(tex0, linear_sampler), vec4(_527, 0.0, 0.0).xy, 0.0).xyz;
                            float _545;
                            do
                            {
                                if (_190)
                                {
                                    _545 = dot(_535, vec3(0.2989999949932098388671875, 0.58700001239776611328125, 0.114000000059604644775390625));
                                    break;
                                }
                                else
                                {
                                    _545 = dot(abs(_175 - _535), vec3(0.2989999949932098388671875, 0.58700001239776611328125, 0.114000000059604644775390625));
                                    break;
                                }
                                break; // unreachable workaround
                            } while(false);
                            float _546 = _545 - _491;
                            _507 = _527;
                            _511 = abs(_546) >= _488;
                            _515 = _546;
                        }
                        else
                        {
                            _507 = _506;
                            _511 = _510;
                            _515 = _514;
                        }
                        if (!_508)
                        {
                            vec2 _552 = _503 + _438;
                            vec3 _560 = textureLod(sampler2D(tex0, linear_sampler), vec4(_552, 0.0, 0.0).xy, 0.0).xyz;
                            float _570;
                            do
                            {
                                if (_190)
                                {
                                    _570 = dot(_560, vec3(0.2989999949932098388671875, 0.58700001239776611328125, 0.114000000059604644775390625));
                                    break;
                                }
                                else
                                {
                                    _570 = dot(abs(_175 - _560), vec3(0.2989999949932098388671875, 0.58700001239776611328125, 0.114000000059604644775390625));
                                    break;
                                }
                                break; // unreachable workaround
                            } while(false);
                            float _571 = _570 - _491;
                            _504 = _552;
                            _509 = abs(_571) >= _488;
                            _517 = _571;
                        }
                        else
                        {
                            _504 = _503;
                            _509 = _508;
                            _517 = _516;
                        }
                        _513 = _512 + 1u;
                    }
                    _574 = _503;
                    _575 = _506;
                    _576 = _514;
                    _577 = _516;
                }
                else
                {
                    _574 = _450;
                    _575 = _449;
                    _576 = _492;
                    _577 = _493;
                }
                vec2 _582 = vec2(_169 - _575.y, _574.y - _169);
                vec2 _590;
                SPIRV_CROSS_FLATTEN
                if (_348)
                {
                    vec2 _589 = _582;
                    _589.x = _168 - _575.x;
                    _590 = _589;
                }
                else
                {
                    _590 = _582;
                }
                vec2 _594;
                SPIRV_CROSS_FLATTEN
                if (_348)
                {
                    vec2 _593 = _590;
                    _593.y = _574.x - _168;
                    _594 = _593;
                }
                else
                {
                    _594 = _590;
                }
                bool _605;
                if (_594.x < _594.y)
                {
                    _605 = (_576 < 0.0) != _490;
                }
                else
                {
                    _605 = (_577 < 0.0) != _490;
                }
                precise float _28 = fma((-1.0) / (_594.y + _594.x), spvNMin(_594.x, _594.y), 0.5);
                float _624;
                SPIRV_CROSS_BRANCH
                if (!_605)
                {
                    float _617 = fma(fma(2.0, _335 + _338, _334 + _336), 0.08333300054073333740234375, -_192) * (1.0 / _267);
                    _624 = (pow(clamp(fma(-2.0, _617, 3.0) * (_617 * _617), 0.0, 1.0), 2.0) * _401) * _28;
                }
                else
                {
                    _624 = _28 * _401;
                }
                precise vec2 _32 = fma(vec2(_426), vec2(_624), _113);
                vec2 _631;
                SPIRV_CROSS_FLATTEN
                if (_403)
                {
                    vec2 _630 = _113;
                    _630.x = _32.x;
                    _631 = _630;
                }
                else
                {
                    _631 = _113;
                }
                vec2 _636;
                SPIRV_CROSS_FLATTEN
                if (_348)
                {
                    vec2 _635 = _631;
                    _635.y = _32.y;
                    _636 = _635;
                }
                else
                {
                    _636 = _631;
                }
                _645 = textureLod(sampler2D(tex0, linear_sampler), vec4(_636, 0.0, 0.0).xy, 0.0).xyz;
                break;
            } while(false);
            _646 = _645;
            _647 = false;
            break;
        } while(false);
        vec4 _655;
        if (_647)
        {
            _655 = _117;
        }
        else
        {
            _655 = vec4(_646, 1.0);
        }
        imageStore(output0, ivec2(gl_GlobalInvocationID.xy), _655);
        break;
    } while(false);
}
