// SPDX-FileCopyrightText: Copyright 2025 RdenBlaauwen; Jorge Jimenez et al.; NVIDIA Corporation; Derek Brush
// SPDX-License-Identifier: LicenseRef-PSMAA-ThirdParty

#version 450
#extension GL_EXT_spirv_intrinsics : require
#ifndef PSMAA_LUMA_FORMAT
#define PSMAA_LUMA_FORMAT r16f
#endif
#ifndef PSMAA_VECTOR_FORMAT
#define PSMAA_VECTOR_FORMAT rg16f
#endif
#ifndef CMAA_EDGE_FORMAT
#define CMAA_EDGE_FORMAT r8ui
#endif

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

float _45;

layout(push_constant, std430) uniform type_PushConstant_Constants
{
    vec4 metrics;
    vec4 target;
    uint conversion;
} params;

layout(set = 0, binding = 0) uniform texture2D tex0;
layout(set = 0, binding = 9) uniform sampler linear_sampler;
layout(set = 0, binding = 10, PSMAA_VECTOR_FORMAT) uniform writeonly image2D output0;

spirv_instruction(set = "GLSL.std.450", id = 79) float spvNMin(float, float);
spirv_instruction(set = "GLSL.std.450", id = 79) vec2 spvNMin(vec2, vec2);
spirv_instruction(set = "GLSL.std.450", id = 79) vec3 spvNMin(vec3, vec3);
spirv_instruction(set = "GLSL.std.450", id = 79) vec4 spvNMin(vec4, vec4);
spirv_instruction(set = "GLSL.std.450", id = 80) float spvNMax(float, float);
spirv_instruction(set = "GLSL.std.450", id = 80) vec2 spvNMax(vec2, vec2);
spirv_instruction(set = "GLSL.std.450", id = 80) vec3 spvNMax(vec3, vec3);
spirv_instruction(set = "GLSL.std.450", id = 80) vec4 spvNMax(vec4, vec4);

void main()
{
    do
    {
        if (any(greaterThanEqual(gl_GlobalInvocationID.xy, uvec2(params.target.zw))))
        {
            break;
        }
        vec2 _64 = (vec2(gl_GlobalInvocationID.xy) + vec2(0.5)) * params.metrics.xy;
        precise vec4 _13 = fma(vec4(params.metrics.x, params.metrics.y, _45, _45).xyxy, vec4(-1.0, 0.0, 0.0, -1.0), _64.xyxy);
        vec4 _75 = textureLod(sampler2D(tex0, linear_sampler), _64, 0.0);
        vec3 _76 = _75.xyz;
        vec4 _80 = textureLod(sampler2D(tex0, linear_sampler), _13.xy, 0.0);
        vec4 _85 = textureLod(sampler2D(tex0, linear_sampler), _13.zw, 0.0);
        float _87 = _75.x;
        float _88 = _75.y;
        float _90 = _75.z;
        float _94 = spvNMax(spvNMax(_87, _88), _90) - spvNMin(spvNMin(_87, _88), _90);
        float _95 = _80.x;
        float _96 = _80.y;
        float _98 = _80.z;
        float _103 = _85.x;
        float _104 = _85.y;
        float _106 = _85.z;
        vec3 _112 = abs(_80.xyz - _76);
        vec3 _122 = abs(_85.xyz - _76);
        imageStore(output0, ivec2(gl_GlobalInvocationID.xy), vec4(mix(dot(_112, vec3(0.2989999949932098388671875, 0.58700001239776611328125, 0.114000000059604644775390625)), spvNMax(spvNMax(_112.x, _112.y), _112.z), spvNMax(spvNMax(spvNMax(_95, _96), _98) - spvNMin(spvNMin(_95, _96), _98), _94)), mix(dot(_122, vec3(0.2989999949932098388671875, 0.58700001239776611328125, 0.114000000059604644775390625)), spvNMax(spvNMax(_122.x, _122.y), _122.z), spvNMax(spvNMax(spvNMax(_103, _104), _106) - spvNMin(spvNMin(_103, _104), _106), _94)), 0.0, 0.0));
        break;
    } while(false);
}
